project:
  type: website
  output-dir: .
  render:
    - index.qmd
    - assessment_rubric.qmd

website:
  navbar:
    logo: /courses/54132/files/101696886.svg
    left:
      - text: "Course Home"
        href: index.html
    right:
      - text: "Assessment Rubric"
        href: assessment_rubric.html

format:
  html:
    theme: rsm.scss
    css: styles.css
    toc: false
