project:
  type: website
  output-dir: .
  render:
    - index.qmd
    - add_content.qmd

website:
  navbar:
    right:
      - text: "Additional Content"
        href: add_content.html

format:
  html:
    theme: rsm.scss
    css: styles.css
    toc: false
